# Generated by Django 5.1.3 on 2024-11-30 05:15

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='images/'),
        ),
    ]
