# Generated by Django 5.1.3 on 2024-11-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='condition',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sale_handling',
            field=models.CharField(default='pickup', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
