# Generated by Django 5.1.3 on 2024-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
